###
GET http://localhost:8888/verify
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYwMjk1MjIsImV4cCI6MTYwNjAzMzEyMiwiYXVkIjoiNWZiOGE3ZDZmODE5MzUyMWYwOTY3YWM5IiwiaXNzIjoiaW1zYW1hZC5jb20ifQ.gckhEyZAROeLoLa0rQnksOf1KGHjsFTEe2MerS6di7M

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
    "email":"one@gmail.com",
    "password":"first"
}   

###
POST http://localhost:8888/auth/register
Content-Type: application/json

{
    "email":"chks8@gmail.com",
    "password":"first"
}

###

###
DELETE  http://localhost:8888/auth/logout
Content-Type: application/json

{
    "delUser":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYwMjk1MjIsImV4cCI6MTYzNzU4NzEyMiwiYXVkIjoiNWZiOGE3ZDZmODE5MzUyMWYwOTY3YWM5IiwiaXNzIjoiaW1zYW1hZC5jb20ifQ.LUoB0TWOo0Gg7ljcVlkL0cISPQf7Wb-YH6qXNe9DwvA"
}

###

###
POST http://localhost:8888/auth/refresh-token
Content-Type: application/json

{
    "refToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYwMjgwMjAsImV4cCI6MTYzNzU4NTYyMCwiYXVkIjoiNWZiOGE3ZDZmODE5MzUyMWYwOTY3YWM5IiwiaXNzIjoiaW1zYW1hZC5jb20ifQ.8Z-IRLcS3kO3Jd1qC1yiMpMvSZWTWXqV4_06TXEYxfQ"
}
###

###
GET http://localhost:8888/auth/all
