###
GET http://localhost:5000/api/v1/bootcamps

###
POST http://localhost:5000/api/v1/bootcamps

###
DELETE http://localhost:5000/api/v1/bootcamps/4454

### 
PUT http://localhost:5000/api/v1/bootcamps/3545